.PHONY: proto
proto: proto_dart proto_go

proto_go_deps:
	go get github.com/gogo/protobuf/protoc-gen-gofast

proto_dart_deps:
	flutter pub global activate protoc_plugin

proto_dart:
	rm -rf output/dart && mkdir -p output/dart
	protoc -Iproto --dart_out=grpc:./output/dart proto/*.proto
proto_go:
	rm -rf bridge/model && mkdir -p bridge/model
	protoc -Iproto --gofast_out=grpc:./bridge/model proto/*.proto
