DARWIN_OUTPUT?=darwin
DARWIN_BINDING_OUTPUT?=$(BINDING_OUTPUT)/$(DARWIN_OUTPUT)

binding_darwin: binding_darwin_x86_64

binding_darwin_x86_64:
	BINDING_FILE=$(DARWIN_OUTPUT)/$(BINDING_NAME).a \
	BUILD_MODE="c-archive" \
	CGO_CFLAGS=-mmacosx-version-min=10.11 \
	GOOS=darwin GOARCH=amd64 CGO_ENABLED=1 \
	make binding
