.PHONY: wasm
wasm:
	mkdir -p output/wasm
	tinygo build -o output/wasm/openpgp.wasm -target wasm wasm/main.go
	cp $(GOROOT)/misc/wasm/wasm_exec.js  output/wasm/wasm_exec.js
	cp output/wasm/openpgp.wasm wasm/sample/public/openpgp.wasm
	cp output/wasm/wasm_exec.js  wasm/sample/public/wasm_exec.js