.PHONY: proto
proto: proto-dart proto-go
proto-deps:
	go get github.com/gogo/protobuf/protoc-gen-gofast
	flutter pub global activate protoc_plugin

proto-dart:
	rm -rf output/dart && mkdir -p output/dart
	protoc -Iproto --dart_out=grpc:./output/dart proto/*.proto
proto-go:
	rm -rf bridge/model && mkdir -p bridge/model
	protoc -Iproto --gofast_out=grpc:./bridge/model proto/*.proto
