// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import "strconv"

type Algorithm int32

const (
	AlgorithmRSA     Algorithm = 0
	AlgorithmECDSA   Algorithm = 1
	AlgorithmEDDSA   Algorithm = 2
	AlgorithmECHD    Algorithm = 3
	AlgorithmDSA     Algorithm = 4
	AlgorithmELGAMAL Algorithm = 5
)

var EnumNamesAlgorithm = map[Algorithm]string{
	AlgorithmRSA:     "RSA",
	AlgorithmECDSA:   "ECDSA",
	AlgorithmEDDSA:   "EDDSA",
	AlgorithmECHD:    "ECHD",
	AlgorithmDSA:     "DSA",
	AlgorithmELGAMAL: "ELGAMAL",
}

var EnumValuesAlgorithm = map[string]Algorithm{
	"RSA":     AlgorithmRSA,
	"ECDSA":   AlgorithmECDSA,
	"EDDSA":   AlgorithmEDDSA,
	"ECHD":    AlgorithmECHD,
	"DSA":     AlgorithmDSA,
	"ELGAMAL": AlgorithmELGAMAL,
}

func (v Algorithm) String() string {
	if s, ok := EnumNamesAlgorithm[v]; ok {
		return s
	}
	return "Algorithm(" + strconv.FormatInt(int64(v), 10) + ")"
}
