// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ArmorDecodeResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsArmorDecodeResponse(buf []byte, offset flatbuffers.UOffsetT) *ArmorDecodeResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ArmorDecodeResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishArmorDecodeResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsArmorDecodeResponse(buf []byte, offset flatbuffers.UOffsetT) *ArmorDecodeResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ArmorDecodeResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedArmorDecodeResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ArmorDecodeResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ArmorDecodeResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ArmorDecodeResponse) Output(obj *ArmorMetadata) *ArmorMetadata {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ArmorMetadata)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ArmorDecodeResponse) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ArmorDecodeResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ArmorDecodeResponseAddOutput(builder *flatbuffers.Builder, output flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(output), 0)
}
func ArmorDecodeResponseAddError(builder *flatbuffers.Builder, error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(error), 0)
}
func ArmorDecodeResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
