// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ArmorEncodeRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsArmorEncodeRequest(buf []byte, offset flatbuffers.UOffsetT) *ArmorEncodeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ArmorEncodeRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsArmorEncodeRequest(buf []byte, offset flatbuffers.UOffsetT) *ArmorEncodeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ArmorEncodeRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ArmorEncodeRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ArmorEncodeRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ArmorEncodeRequest) Packet(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ArmorEncodeRequest) PacketLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ArmorEncodeRequest) PacketBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ArmorEncodeRequest) MutatePacket(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func ArmorEncodeRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ArmorEncodeRequestAddPacket(builder *flatbuffers.Builder, packet flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(packet), 0)
}
func ArmorEncodeRequestStartPacketVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ArmorEncodeRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
