// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BoolResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsBoolResponse(buf []byte, offset flatbuffers.UOffsetT) *BoolResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BoolResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsBoolResponse(buf []byte, offset flatbuffers.UOffsetT) *BoolResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BoolResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *BoolResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BoolResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BoolResponse) Output() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *BoolResponse) MutateOutput(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *BoolResponse) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func BoolResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func BoolResponseAddOutput(builder *flatbuffers.Builder, output bool) {
	builder.PrependBoolSlot(0, output, false)
}
func BoolResponseAddError(builder *flatbuffers.Builder, error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(error), 0)
}
func BoolResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
