// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import "strconv"

type Cipher int32

const (
	CipherCIPHER_UNSPECIFIED Cipher = 0
	CipherCIPHER_AES128      Cipher = 1
	CipherCIPHER_AES192      Cipher = 2
	CipherCIPHER_AES256      Cipher = 3
)

var EnumNamesCipher = map[Cipher]string{
	CipherCIPHER_UNSPECIFIED: "CIPHER_UNSPECIFIED",
	CipherCIPHER_AES128:      "CIPHER_AES128",
	CipherCIPHER_AES192:      "CIPHER_AES192",
	CipherCIPHER_AES256:      "CIPHER_AES256",
}

var EnumValuesCipher = map[string]Cipher{
	"CIPHER_UNSPECIFIED": CipherCIPHER_UNSPECIFIED,
	"CIPHER_AES128":      CipherCIPHER_AES128,
	"CIPHER_AES192":      CipherCIPHER_AES192,
	"CIPHER_AES256":      CipherCIPHER_AES256,
}

func (v Cipher) String() string {
	if s, ok := EnumNamesCipher[v]; ok {
		return s
	}
	return "Cipher(" + strconv.FormatInt(int64(v), 10) + ")"
}
