// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import "strconv"

type Compression int32

const (
	CompressionCOMPRESSION_UNSPECIFIED Compression = 0
	CompressionCOMPRESSION_NONE        Compression = 1
	CompressionCOMPRESSION_ZLIB        Compression = 2
	CompressionCOMPRESSION_ZIP         Compression = 3
)

var EnumNamesCompression = map[Compression]string{
	CompressionCOMPRESSION_UNSPECIFIED: "COMPRESSION_UNSPECIFIED",
	CompressionCOMPRESSION_NONE:        "COMPRESSION_NONE",
	CompressionCOMPRESSION_ZLIB:        "COMPRESSION_ZLIB",
	CompressionCOMPRESSION_ZIP:         "COMPRESSION_ZIP",
}

var EnumValuesCompression = map[string]Compression{
	"COMPRESSION_UNSPECIFIED": CompressionCOMPRESSION_UNSPECIFIED,
	"COMPRESSION_NONE":        CompressionCOMPRESSION_NONE,
	"COMPRESSION_ZLIB":        CompressionCOMPRESSION_ZLIB,
	"COMPRESSION_ZIP":         CompressionCOMPRESSION_ZIP,
}

func (v Compression) String() string {
	if s, ok := EnumNamesCompression[v]; ok {
		return s
	}
	return "Compression(" + strconv.FormatInt(int64(v), 10) + ")"
}
