// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import "strconv"

type Compression int32

const (
	CompressionNONE Compression = 0
	CompressionZLIB Compression = 1
	CompressionZIP  Compression = 2
)

var EnumNamesCompression = map[Compression]string{
	CompressionNONE: "NONE",
	CompressionZLIB: "ZLIB",
	CompressionZIP:  "ZIP",
}

var EnumValuesCompression = map[string]Compression{
	"NONE": CompressionNONE,
	"ZLIB": CompressionZLIB,
	"ZIP":  CompressionZIP,
}

func (v Compression) String() string {
	if s, ok := EnumNamesCompression[v]; ok {
		return s
	}
	return "Compression(" + strconv.FormatInt(int64(v), 10) + ")"
}
