// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ConvertPrivateKeyToPublicKeyRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsConvertPrivateKeyToPublicKeyRequest(buf []byte, offset flatbuffers.UOffsetT) *ConvertPrivateKeyToPublicKeyRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConvertPrivateKeyToPublicKeyRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsConvertPrivateKeyToPublicKeyRequest(buf []byte, offset flatbuffers.UOffsetT) *ConvertPrivateKeyToPublicKeyRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConvertPrivateKeyToPublicKeyRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ConvertPrivateKeyToPublicKeyRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConvertPrivateKeyToPublicKeyRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConvertPrivateKeyToPublicKeyRequest) PrivateKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ConvertPrivateKeyToPublicKeyRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ConvertPrivateKeyToPublicKeyRequestAddPrivateKey(builder *flatbuffers.Builder, privateKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(privateKey), 0)
}
func ConvertPrivateKeyToPublicKeyRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
