// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetPrivateKeyMetadataRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsGetPrivateKeyMetadataRequest(buf []byte, offset flatbuffers.UOffsetT) *GetPrivateKeyMetadataRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetPrivateKeyMetadataRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishGetPrivateKeyMetadataRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGetPrivateKeyMetadataRequest(buf []byte, offset flatbuffers.UOffsetT) *GetPrivateKeyMetadataRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GetPrivateKeyMetadataRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGetPrivateKeyMetadataRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GetPrivateKeyMetadataRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetPrivateKeyMetadataRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetPrivateKeyMetadataRequest) PrivateKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func GetPrivateKeyMetadataRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GetPrivateKeyMetadataRequestAddPrivateKey(builder *flatbuffers.Builder, privateKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(privateKey), 0)
}
func GetPrivateKeyMetadataRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
