// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import "strconv"

type Hash int32

const (
	HashHASH_UNSPECIFIED Hash = 0
	HashHASH_SHA256      Hash = 1
	HashHASH_SHA224      Hash = 2
	HashHASH_SHA384      Hash = 3
	HashHASH_SHA512      Hash = 4
)

var EnumNamesHash = map[Hash]string{
	HashHASH_UNSPECIFIED: "HASH_UNSPECIFIED",
	HashHASH_SHA256:      "HASH_SHA256",
	HashHASH_SHA224:      "HASH_SHA224",
	HashHASH_SHA384:      "HASH_SHA384",
	HashHASH_SHA512:      "HASH_SHA512",
}

var EnumValuesHash = map[string]Hash{
	"HASH_UNSPECIFIED": HashHASH_UNSPECIFIED,
	"HASH_SHA256":      HashHASH_SHA256,
	"HASH_SHA224":      HashHASH_SHA224,
	"HASH_SHA384":      HashHASH_SHA384,
	"HASH_SHA512":      HashHASH_SHA512,
}

func (v Hash) String() string {
	if s, ok := EnumNamesHash[v]; ok {
		return s
	}
	return "Hash(" + strconv.FormatInt(int64(v), 10) + ")"
}
