// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KeyPairResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsKeyPairResponse(buf []byte, offset flatbuffers.UOffsetT) *KeyPairResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KeyPairResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsKeyPairResponse(buf []byte, offset flatbuffers.UOffsetT) *KeyPairResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KeyPairResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *KeyPairResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KeyPairResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KeyPairResponse) Output(obj *KeyPair) *KeyPair {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(KeyPair)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *KeyPairResponse) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func KeyPairResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func KeyPairResponseAddOutput(builder *flatbuffers.Builder, output flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(output), 0)
}
func KeyPairResponseAddError(builder *flatbuffers.Builder, error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(error), 0)
}
func KeyPairResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
