// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PrivateKeyMetadata struct {
	_tab flatbuffers.Table
}

func GetRootAsPrivateKeyMetadata(buf []byte, offset flatbuffers.UOffsetT) *PrivateKeyMetadata {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PrivateKeyMetadata{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsPrivateKeyMetadata(buf []byte, offset flatbuffers.UOffsetT) *PrivateKeyMetadata {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PrivateKeyMetadata{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *PrivateKeyMetadata) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PrivateKeyMetadata) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PrivateKeyMetadata) KeyId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PrivateKeyMetadata) KeyIdShort() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PrivateKeyMetadata) CreationTime() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PrivateKeyMetadata) Fingerprint() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PrivateKeyMetadata) KeyIdNumeric() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PrivateKeyMetadata) IsSubKey() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *PrivateKeyMetadata) MutateIsSubKey(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

func (rcv *PrivateKeyMetadata) Encrypted() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *PrivateKeyMetadata) MutateEncrypted(n bool) bool {
	return rcv._tab.MutateBoolSlot(16, n)
}

func (rcv *PrivateKeyMetadata) Identities(obj *Identity, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PrivateKeyMetadata) IdentitiesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func PrivateKeyMetadataStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func PrivateKeyMetadataAddKeyId(builder *flatbuffers.Builder, keyId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(keyId), 0)
}
func PrivateKeyMetadataAddKeyIdShort(builder *flatbuffers.Builder, keyIdShort flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(keyIdShort), 0)
}
func PrivateKeyMetadataAddCreationTime(builder *flatbuffers.Builder, creationTime flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(creationTime), 0)
}
func PrivateKeyMetadataAddFingerprint(builder *flatbuffers.Builder, fingerprint flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(fingerprint), 0)
}
func PrivateKeyMetadataAddKeyIdNumeric(builder *flatbuffers.Builder, keyIdNumeric flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(keyIdNumeric), 0)
}
func PrivateKeyMetadataAddIsSubKey(builder *flatbuffers.Builder, isSubKey bool) {
	builder.PrependBoolSlot(5, isSubKey, false)
}
func PrivateKeyMetadataAddEncrypted(builder *flatbuffers.Builder, encrypted bool) {
	builder.PrependBoolSlot(6, encrypted, false)
}
func PrivateKeyMetadataAddIdentities(builder *flatbuffers.Builder, identities flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(identities), 0)
}
func PrivateKeyMetadataStartIdentitiesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PrivateKeyMetadataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
