// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PublicKeyMetadataResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsPublicKeyMetadataResponse(buf []byte, offset flatbuffers.UOffsetT) *PublicKeyMetadataResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PublicKeyMetadataResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsPublicKeyMetadataResponse(buf []byte, offset flatbuffers.UOffsetT) *PublicKeyMetadataResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PublicKeyMetadataResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *PublicKeyMetadataResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PublicKeyMetadataResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PublicKeyMetadataResponse) Output(obj *PublicKeyMetadata) *PublicKeyMetadata {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(PublicKeyMetadata)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *PublicKeyMetadataResponse) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PublicKeyMetadataResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PublicKeyMetadataResponseAddOutput(builder *flatbuffers.Builder, output flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(output), 0)
}
func PublicKeyMetadataResponseAddError(builder *flatbuffers.Builder, error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(error), 0)
}
func PublicKeyMetadataResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
