/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: binding/openpgp_bridge/openpgp_bridge.i

#define SWIGMODULE openpgp_bridge

#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include "openpgp_bridge.h"


#include <string>


#include <vector>
#include <stdexcept>

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_openpgp_bridge_88449df1d0366082(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_openpgp_bridge_88449df1d0366082(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_KeyPair_publicKey_set_openpgp_bridge_88449df1d0366082(KeyPair *_swig_go_0, _gostring_ _swig_go_1) {
  KeyPair *arg1 = (KeyPair *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = *(KeyPair **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    delete [] arg1->publicKey;
    if (arg2) {
      arg1->publicKey = (char *) (new char[strlen((const char *)arg2)+1]);
      strcpy((char *)arg1->publicKey, (const char *)arg2);
    } else {
      arg1->publicKey = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_KeyPair_publicKey_get_openpgp_bridge_88449df1d0366082(KeyPair *_swig_go_0) {
  KeyPair *arg1 = (KeyPair *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(KeyPair **)&_swig_go_0; 
  
  result = (char *) ((arg1)->publicKey);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_KeyPair_privateKey_set_openpgp_bridge_88449df1d0366082(KeyPair *_swig_go_0, _gostring_ _swig_go_1) {
  KeyPair *arg1 = (KeyPair *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = *(KeyPair **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    delete [] arg1->privateKey;
    if (arg2) {
      arg1->privateKey = (char *) (new char[strlen((const char *)arg2)+1]);
      strcpy((char *)arg1->privateKey, (const char *)arg2);
    } else {
      arg1->privateKey = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_KeyPair_privateKey_get_openpgp_bridge_88449df1d0366082(KeyPair *_swig_go_0) {
  KeyPair *arg1 = (KeyPair *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(KeyPair **)&_swig_go_0; 
  
  result = (char *) ((arg1)->privateKey);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


KeyPair *_wrap_new_KeyPair_openpgp_bridge_88449df1d0366082() {
  KeyPair *result = 0 ;
  KeyPair *_swig_go_result;
  
  
  result = (KeyPair *)new KeyPair();
  *(KeyPair **)&_swig_go_result = (KeyPair *)result; 
  return _swig_go_result;
}


void _wrap_delete_KeyPair_openpgp_bridge_88449df1d0366082(KeyPair *_swig_go_0) {
  KeyPair *arg1 = (KeyPair *) 0 ;
  
  arg1 = *(KeyPair **)&_swig_go_0; 
  
  delete arg1;
  
}


void _wrap_KeyOptions_hash_set_openpgp_bridge_88449df1d0366082(KeyOptions *_swig_go_0, _gostring_ _swig_go_1) {
  KeyOptions *arg1 = (KeyOptions *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = *(KeyOptions **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    delete [] arg1->hash;
    if (arg2) {
      arg1->hash = (char *) (new char[strlen((const char *)arg2)+1]);
      strcpy((char *)arg1->hash, (const char *)arg2);
    } else {
      arg1->hash = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_KeyOptions_hash_get_openpgp_bridge_88449df1d0366082(KeyOptions *_swig_go_0) {
  KeyOptions *arg1 = (KeyOptions *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(KeyOptions **)&_swig_go_0; 
  
  result = (char *) ((arg1)->hash);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_KeyOptions_cipher_set_openpgp_bridge_88449df1d0366082(KeyOptions *_swig_go_0, _gostring_ _swig_go_1) {
  KeyOptions *arg1 = (KeyOptions *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = *(KeyOptions **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    delete [] arg1->cipher;
    if (arg2) {
      arg1->cipher = (char *) (new char[strlen((const char *)arg2)+1]);
      strcpy((char *)arg1->cipher, (const char *)arg2);
    } else {
      arg1->cipher = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_KeyOptions_cipher_get_openpgp_bridge_88449df1d0366082(KeyOptions *_swig_go_0) {
  KeyOptions *arg1 = (KeyOptions *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(KeyOptions **)&_swig_go_0; 
  
  result = (char *) ((arg1)->cipher);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_KeyOptions_compression_set_openpgp_bridge_88449df1d0366082(KeyOptions *_swig_go_0, _gostring_ _swig_go_1) {
  KeyOptions *arg1 = (KeyOptions *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = *(KeyOptions **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    delete [] arg1->compression;
    if (arg2) {
      arg1->compression = (char *) (new char[strlen((const char *)arg2)+1]);
      strcpy((char *)arg1->compression, (const char *)arg2);
    } else {
      arg1->compression = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_KeyOptions_compression_get_openpgp_bridge_88449df1d0366082(KeyOptions *_swig_go_0) {
  KeyOptions *arg1 = (KeyOptions *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(KeyOptions **)&_swig_go_0; 
  
  result = (char *) ((arg1)->compression);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_KeyOptions_compressionLevel_set_openpgp_bridge_88449df1d0366082(KeyOptions *_swig_go_0, _gostring_ _swig_go_1) {
  KeyOptions *arg1 = (KeyOptions *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = *(KeyOptions **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    delete [] arg1->compressionLevel;
    if (arg2) {
      arg1->compressionLevel = (char *) (new char[strlen((const char *)arg2)+1]);
      strcpy((char *)arg1->compressionLevel, (const char *)arg2);
    } else {
      arg1->compressionLevel = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_KeyOptions_compressionLevel_get_openpgp_bridge_88449df1d0366082(KeyOptions *_swig_go_0) {
  KeyOptions *arg1 = (KeyOptions *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(KeyOptions **)&_swig_go_0; 
  
  result = (char *) ((arg1)->compressionLevel);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_KeyOptions_rsaBits_set_openpgp_bridge_88449df1d0366082(KeyOptions *_swig_go_0, _gostring_ _swig_go_1) {
  KeyOptions *arg1 = (KeyOptions *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = *(KeyOptions **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    delete [] arg1->rsaBits;
    if (arg2) {
      arg1->rsaBits = (char *) (new char[strlen((const char *)arg2)+1]);
      strcpy((char *)arg1->rsaBits, (const char *)arg2);
    } else {
      arg1->rsaBits = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_KeyOptions_rsaBits_get_openpgp_bridge_88449df1d0366082(KeyOptions *_swig_go_0) {
  KeyOptions *arg1 = (KeyOptions *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(KeyOptions **)&_swig_go_0; 
  
  result = (char *) ((arg1)->rsaBits);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


KeyOptions *_wrap_new_KeyOptions_openpgp_bridge_88449df1d0366082() {
  KeyOptions *result = 0 ;
  KeyOptions *_swig_go_result;
  
  
  result = (KeyOptions *)new KeyOptions();
  *(KeyOptions **)&_swig_go_result = (KeyOptions *)result; 
  return _swig_go_result;
}


void _wrap_delete_KeyOptions_openpgp_bridge_88449df1d0366082(KeyOptions *_swig_go_0) {
  KeyOptions *arg1 = (KeyOptions *) 0 ;
  
  arg1 = *(KeyOptions **)&_swig_go_0; 
  
  delete arg1;
  
}


void _wrap_Options_name_set_openpgp_bridge_88449df1d0366082(Options *_swig_go_0, _gostring_ _swig_go_1) {
  Options *arg1 = (Options *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = *(Options **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    delete [] arg1->name;
    if (arg2) {
      arg1->name = (char *) (new char[strlen((const char *)arg2)+1]);
      strcpy((char *)arg1->name, (const char *)arg2);
    } else {
      arg1->name = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_Options_name_get_openpgp_bridge_88449df1d0366082(Options *_swig_go_0) {
  Options *arg1 = (Options *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(Options **)&_swig_go_0; 
  
  result = (char *) ((arg1)->name);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_Options_comment_set_openpgp_bridge_88449df1d0366082(Options *_swig_go_0, _gostring_ _swig_go_1) {
  Options *arg1 = (Options *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = *(Options **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    delete [] arg1->comment;
    if (arg2) {
      arg1->comment = (char *) (new char[strlen((const char *)arg2)+1]);
      strcpy((char *)arg1->comment, (const char *)arg2);
    } else {
      arg1->comment = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_Options_comment_get_openpgp_bridge_88449df1d0366082(Options *_swig_go_0) {
  Options *arg1 = (Options *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(Options **)&_swig_go_0; 
  
  result = (char *) ((arg1)->comment);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_Options_email_set_openpgp_bridge_88449df1d0366082(Options *_swig_go_0, _gostring_ _swig_go_1) {
  Options *arg1 = (Options *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = *(Options **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    delete [] arg1->email;
    if (arg2) {
      arg1->email = (char *) (new char[strlen((const char *)arg2)+1]);
      strcpy((char *)arg1->email, (const char *)arg2);
    } else {
      arg1->email = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_Options_email_get_openpgp_bridge_88449df1d0366082(Options *_swig_go_0) {
  Options *arg1 = (Options *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(Options **)&_swig_go_0; 
  
  result = (char *) ((arg1)->email);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_Options_passphrase_set_openpgp_bridge_88449df1d0366082(Options *_swig_go_0, _gostring_ _swig_go_1) {
  Options *arg1 = (Options *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = *(Options **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    delete [] arg1->passphrase;
    if (arg2) {
      arg1->passphrase = (char *) (new char[strlen((const char *)arg2)+1]);
      strcpy((char *)arg1->passphrase, (const char *)arg2);
    } else {
      arg1->passphrase = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_Options_passphrase_get_openpgp_bridge_88449df1d0366082(Options *_swig_go_0) {
  Options *arg1 = (Options *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(Options **)&_swig_go_0; 
  
  result = (char *) ((arg1)->passphrase);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_Options_keyOptions_set_openpgp_bridge_88449df1d0366082(Options *_swig_go_0, KeyOptions *_swig_go_1) {
  Options *arg1 = (Options *) 0 ;
  KeyOptions *arg2 = (KeyOptions *) 0 ;
  
  arg1 = *(Options **)&_swig_go_0; 
  arg2 = *(KeyOptions **)&_swig_go_1; 
  
  if (arg1) (arg1)->keyOptions = arg2;
  
}


KeyOptions *_wrap_Options_keyOptions_get_openpgp_bridge_88449df1d0366082(Options *_swig_go_0) {
  Options *arg1 = (Options *) 0 ;
  KeyOptions *result = 0 ;
  KeyOptions *_swig_go_result;
  
  arg1 = *(Options **)&_swig_go_0; 
  
  result = (KeyOptions *) ((arg1)->keyOptions);
  *(KeyOptions **)&_swig_go_result = (KeyOptions *)result; 
  return _swig_go_result;
}


Options *_wrap_new_Options_openpgp_bridge_88449df1d0366082() {
  Options *result = 0 ;
  Options *_swig_go_result;
  
  
  result = (Options *)new Options();
  *(Options **)&_swig_go_result = (Options *)result; 
  return _swig_go_result;
}


void _wrap_delete_Options_openpgp_bridge_88449df1d0366082(Options *_swig_go_0) {
  Options *arg1 = (Options *) 0 ;
  
  arg1 = *(Options **)&_swig_go_0; 
  
  delete arg1;
  
}


void _wrap_errorGenerateThrow_openpgp_bridge_88449df1d0366082(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  errorGenerateThrow(arg1);
  
  free(arg1); 
}


KeyPair *_wrap_create_keyPair_openpgp_bridge_88449df1d0366082(_gostring_ _swig_go_0, _gostring_ _swig_go_1) {
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  KeyPair *result = 0 ;
  KeyPair *_swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (KeyPair *)create_keyPair(arg1,arg2);
  *(KeyPair **)&_swig_go_result = (KeyPair *)result; 
  free(arg1); 
  free(arg2); 
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

